#!/bin/bash

set -e

case "$1" in
    configure)
        LOGDIR="/var/log/atop"
        touch $LOGDIR/dummy_after $LOGDIR/dummy_before
        DATE="$(date +%Y%m%d)"
        # check whether atop will read its own latest file
        # point atop to the latest file and check for output on stdout
        # the pipe will prevent atop from going interactive, and if it
        # won't read the file, stdout will be empty.
        if ls -t $LOGDIR/atop_${DATE} > /dev/null 2>&1; then
            LATESTFILE="/var/log/atop/atop_${DATE}"
            if ! atop -r $LATESTFILE 2>/dev/null | head -n 5 | grep -q '.'; then
                mv "/var/log/atop/atop_${DATE}" "/var/log/atop/atop_${DATE}_old"
            fi
        fi
    ;;
esac

#DEBHELPER#

# vim: tabstop=4 expandtab

